import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";

import { Suspense } from "react";
import Loading from "./loading";
import Header from "@/components/Header";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Base Pathner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
        style={{ scrollBehavior: "smooth" }}
      >
        <Providers>
          <Suspense fallback={<Loading />}>
            <Header />
            {children}
            <Toaster />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
